packages:
  all:
    #target: [x86_64]
    compiler: [apple-clang, gcc, clang]
    variants: build_type=Release
    providers:
      mpi: [openmpi, mpich]
      blas: [netlib-lapack]
      lapack: [netlib-lapack]
